name: ActEV_Scorer_py3.8
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - matplotlib=3.1.3
  - scipy=1.4.1
  - munkres=1.0.12
  - jsonschema=3.2.0
  - dill=0.3.1.1
  - pillow=8.2.0
  - pandas=1.2.4
